execute_process(COMMAND "${PROGRAM}" "${MODE}"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT "${result}" STREQUAL "0")
  message(FATAL_ERROR "Color test failed: ${result}: ${output}\n${error}")
endif()
string(ASCII 27 escape)
foreach(stream IN ITEMS output error)
  string(FIND "${${stream}}" "${escape}[" position)
  if(MODE STREQUAL "always")
    if(position EQUAL -1)
      message(FATAL_ERROR "Forced color missing from ${stream}: ${${stream}}")
    endif()
  elseif(NOT position EQUAL -1)
    message(FATAL_ERROR "Unexpected ANSI color in ${stream}: ${${stream}}")
  endif()
endforeach()
if(NOT output MATCHES "Actual values: 1 != 2" OR NOT output MATCHES "ColorSuccess"
    OR NOT error MATCHES "stderr diagnostic")
  message(FATAL_ERROR "Missing color-test diagnostics: ${output}\n${error}")
endif()
