execute_process(COMMAND "${PROGRAM}" ${ARGUMENTS}
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT "${result}" STREQUAL "${EXPECTED_EXIT}")
  message(FATAL_ERROR "Expected exit ${EXPECTED_EXIT}, got ${result}:\n${output}\n${error}")
endif()
string(ASCII 27 escape)
string(FIND "${output}${error}" "${escape}[" color_position)
if(NOT color_position EQUAL -1)
  message(FATAL_ERROR "Redirected runner output contains ANSI colors: ${output}\n${error}")
endif()
if(NOT "${output}${error}" MATCHES "${EXPECTED_OUTPUT}")
  message(FATAL_ERROR "Missing expected output ${EXPECTED_OUTPUT}:\n${output}\n${error}")
endif()
if(EXPECTED_EXIT EQUAL 1)
  if(NOT output MATCHES "Actual values: 2 != 1")
    message(FATAL_ERROR "Missing operand values: ${output}")
  endif()
  if(NOT output MATCHES "Assertion failed:" OR NOT output MATCHES "runner.cpp:[0-9]+")
    message(FATAL_ERROR "Missing assertion diagnostic or source location: ${output}")
  endif()
  if(NOT output MATCHES "Unexpected exception: runner test error")
    message(FATAL_ERROR "Missing standard exception diagnostic: ${output}")
  endif()
  if(NOT output MATCHES "Unexpected non-standard exception")
    message(FATAL_ERROR "Missing non-standard exception diagnostic: ${output}")
  endif()
  if(NOT output MATCHES "[{]      ok[}][^\n]*Fourth")
    message(FATAL_ERROR "Test after exceptions did not succeed: ${output}")
  endif()
endif()
if("${output}${error}" MATCHES "Sanitizer|runtime error:")
  message(FATAL_ERROR "Sanitizer diagnostic: ${output}\n${error}")
endif()
