execute_process(COMMAND "${PROGRAM}"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT "${result}" STREQUAL "1")
  message(FATAL_ERROR "Duplicate suite must exit 1, got ${result}: ${output}\n${error}")
endif()
if(NOT output MATCHES "Duplicate test name: DuplicateName")
  message(FATAL_ERROR "Missing duplicate name: ${output}")
endif()
if(NOT error MATCHES "Registration failed: 1 duplicate test name[(]s[)]; no tests ran[.]")
  message(FATAL_ERROR "Missing registration summary: ${error}")
endif()
if(output MATCHES "running|suite executed" OR error MATCHES "tests failed|All tests succeeded")
  message(FATAL_ERROR "Invalid suite ran tests or produced a misleading summary: ${output}\n${error}")
endif()
